export const data = [
    {
        adult: false,
        backdrop_path: '/pWsD91G2R1Da3AKM3ymr3UoIfRb.jpg',
        genre_ids: [ 878, 28, 18 ],
        id: 933131,
        original_language: 'ko',
        original_title: '황야',
        overview: 'After a deadly earthquake turns Seoul into a lawless badland, a fearless huntsman springs into action to rescue a teenager abducted by a mad doctor.',
        popularity: 1117.08,
        poster_path: '/zVMyvNowgbsBAL6O6esWfRpAcOb.jpg',
        release_date: '2024-01-26',
        title: 'Badland Hunters',
        video: false,
        vote_average: 6.742,
        vote_count: 449
      },
      {
        adult: false,
        backdrop_path: '/yyFc8Iclt2jxPmLztbP617xXllT.jpg',
        genre_ids: [ 35, 10751, 14 ],
        id: 787699,
        original_language: 'en',
        original_title: 'Wonka',
        overview: 'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.',
        popularity: 972.383,
        poster_path: '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
        release_date: '2023-12-06',
        title: 'Wonka',
        video: false,
        vote_average: 7.218,
        vote_count: 2206
      },
      {
        adult: false,
        backdrop_path: '/A0EqMM4WZpzfxpdoDoqICCpzSQ1.jpg',
        genre_ids: [ 878, 12, 28 ],
        id: 609681,
        original_language: 'en',
        original_title: 'The Marvels',
        overview: 'Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.',
        popularity: 1035.706,
        poster_path: '/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg',
        release_date: '2023-11-08',
        title: 'The Marvels',
        video: false,
        vote_average: 6.265,
        vote_count: 1806
      },
      {
        adult: false,
        backdrop_path: '/unvtbkgxh47BewQ8pENvdOdme0r.jpg',
        genre_ids: [ 28, 18 ],
        id: 1212073,
        original_language: 'de',
        original_title: '60 Minuten',
        overview: 'Desperate to keep custody of his daughter, a mixed martial arts fighter abandons a big match and races across Berlin to attend her birthday party.',
        popularity: 888.011,
        poster_path: '/jojfbnIHGsRpodIood3OQoqA45Y.jpg',
        release_date: '2024-01-19',
        title: 'Sixty Minutes',
        video: false,
        vote_average: 6.877,
        vote_count: 377
      },
      {
        adult: false,
        backdrop_path: '/uUiIGztTrfDhPdAFJpr6m4UBMAd.jpg',
        genre_ids: [ 14, 28, 878 ],
        id: 634492,
        original_language: 'en',
        original_title: 'Madame Web',
        overview: 'Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.',
        popularity: 793.373,
        poster_path: '/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg',
        release_date: '2024-02-14',
        title: 'Madame Web',
        video: false,
        vote_average: 5.4,
        vote_count: 211
      },
]